### ISSUE TITLE
Figura doesn't allow other mods to use b as a keybind even if the action wheel is set to a different key.

### ISSUE THREAD

**Issue by StormDragon-64** [FiguraMC/Figura#154]
Modloader: Forge 43.3.5
MC Version: 1.19.2
Figura Version: 0.1.2
Mods: Sophisticated Core, Sophisticated Backpacks, and Figura.

I was using Figura with Sophisticated Backpacks, and realized that b opened up the action wheel instead of my backpack. So, I changed the keybind for the action wheel to g. The action wheel opened when I pressed g, but pressing b still didn't open my backpack, even though there were now no conflicting keybinds. After disabling Figura and restarting the game, the issue stopped occuring, and I could now open my backpack with b again.
Note: changing the keybind to open your backpack also allows it to open, so Figura is specifically only reserving the b key even when it's not supposed to.

**Comment by TheVeggum** [comment]
If you change any settings / binds it seems Figura causes some sort of issue with saving the data which can cause it to act weird like that, and when you reboot your game it will reset all your mod key binds to their defaults because forge will reset them due to the file being corrupt or something. I'm not an expert or anything this is just my understanding from using the mod and having similar issues and reading around. I really hope they update the mod soon and fix the binding stuff. **_:(_**

**Comment by StormDragon-64** [comment]
I think my issue is different from that one, as the action wheel still opens when I press the new keybinding I set for it and not the old keybind, but still continues to block other mods' actions from happening when I press b.
(Oops, accidently closed the issue.)

**Comment by UnlikePaladin** [comment]
pretty sure this is already fixed on the 0.1.3 release candidates so I'm marking it as fixed but won't close the issue until it fully releases

**Comment by StormDragon-64** [comment]
I could also confirm that the issue doesn't occur for me when using 0.1.3-rc.4.

**Comment by UnlikePaladin** [comment]
Good, yeah, we kinda didn't register keybinds properly before so they were a bit buggy so I made sure to fix that
