### ISSUE TITLE
Figura outdated on quilt

### ISSUE THREAD

**Issue by MochaTheDoe** [FiguraMC/Figura#220]
I downloaded the figura mod and I currently use Quilt on 1.20.4 and it keeps crashing my launcher, so a friend told me I just needed a support ticked to actually use Figura with Quilt

**Comment by UnlikePaladin** [comment]
Thanks for the report, but could you please attach a game log next time, saves a lot of time.

**Comment by MochaTheDoe** [comment]
Oh! sorry, don't exactly know how to do that- I'm so sorry!

**Comment by UnlikePaladin** [comment]
Game logs can be found in the logs directory in .minecraft on clients, or the logs sub-folder of the server directory for servers. We're interested in the file named latest.log, which you upload here.
[https://shockbyte.com/billing/knowledgebase/328/How-to-Find-and-Share-Any-Minecraft-Log.html](https://shockbyte.com/billing/knowledgebase/328/How-to-Find-and-Share-Any-Minecraft-Log.html)
You can probably find video tutorials for it on YT if it's still not clear, because some of our users run the mod on Quilt fine, that's why the log is needed.

**Comment by MochaTheDoe** [comment]
[2024-05-20-7.log.gz](https://github.com/FiguraMC/Figura/files/15382365/2024-05-20-7.log.gz)
Okay I think this is it! It's the most recent in my files, sorry again!

**Comment by MochaTheDoe** [comment]
[crash-2024-05-20_15.43.48.9865-quilt_loader.txt](https://github.com/FiguraMC/Figura/files/15382402/crash-2024-05-20_15.43.48.9865-quilt_loader.txt)
Okay, this should do it, right?

**Comment by KitCat962** [comment]
you are literally using the 1.20.1 jar on 1.20.4.
Figura jars have explicit supported versions. Use the 1.20.4 jar for 1.20.4 minecraft

**Comment by UnlikePaladin** [comment]
The issue is you're using the 1.20.1 version of Figura on Quilt for 1.20.4 they are different Jars because 1.20.4 has many changes inside it so the old version is incompatible, you can find the right one [here on Modrinth](https://modrinth.com/mod/figura/version/0.1.4+1.20.4).

**Comment by UnlikePaladin** [comment]
> you are literally using the 1.20.1 jar on 1.20.4. Figura jars have explicit supported versions. Use the 1.20.4 jar for 1.20.4 minecraft

damn beat me to it lol

**Comment by KitCat962** [comment]
hehehehe

**Comment by UnlikePaladin** [comment]
feel free to reopen the issue if you encounter any other sort of problem or ask on the discord

**Comment by MochaTheDoe** [comment]
sorry sorry sorry feeling really really stupid now

**Comment by UnlikePaladin** [comment]
it's fine don't worry, everyone has these issues sometimes lol
