### ISSUE TITLE
Figura Breaks Mod Nameplates

### ISSUE THREAD

**Issue by PolyframeX** [FiguraMC/Figura#222]
### Bug Description

When using figura, most mods that hide nameplates will stop working, therefore causing nameplates to constantly show.

### Reproduction Steps

1) Install Figura
Install Amerite and equip the mask to see the bug
OR
Install Origins, and origins classes, and select the rogue class. Then see the bug of usernames not hiding behind walls

### Log File

https://pastebin.com/Y5P65j82

**Comment by Sychic** [comment]
For more clarity, this happens due to figura essentially overwriting the vanilla `renderNameTag` method in the [`PlayerRendererMixin`](https://github.com/FiguraMC/Figura/blob/1.20/common/src/main/java/org/figuramc/figura/mixin/render/renderers/PlayerRendererMixin.java). In [`PlayerRendererMixin#renderNameTag`](https://github.com/FiguraMC/Figura/blob/1.20/common/src/main/java/org/figuramc/figura/mixin/render/renderers/PlayerRendererMixin.java#L56), Figura replicates the vanilla name tag rendering process with its own additions and cancels the original method. A more compatible approach would be to separate any additions into separate injections instead of overwriting the vanilla code.
This also breaks [Essential](https://essential.gg)'s icon rendering.

**Comment by LordEnder-Kitty** [comment]
I believe this also breaks [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat)'s talking icons

**Comment by UnlikePaladin** [comment]
The entire logic for this was just rewritten to use Injects and WrapOperations. So it no longer cancels separate injections. SimpleVC not working is a different issue because they too recreate the vanilla "context" transformations and don't actually use the stack's operations so that should be reported to them.
