### ISSUE TITLE
[1.20.1] (Fabric) Incompatability with AdvancedChat (for figura emojis)

### ISSUE THREAD

**Issue by VoidsSpawn** [FiguraMC/Figura#62]
They're not autocompleting or showing in chat. AdvancedChat Modules [Here](https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List)
![image](https://github.com/FiguraMC/Figura/assets/103901826/1768078c-a5aa-434c-8d7d-d73863a95e7b)

**Comment by alekso56** [comment]
This is because AdvancedChat [replaces the chat screen here ](https://github.com/DarkKronicle/AdvancedChatCore/blob/68f0bc2db160b503b50ca36f692217bab41c93ce/src/main/java/io/github/darkkronicle/advancedchatcore/mixin/MixinMinecraftClient.java#L42) 
figura would have to spesifically check the instance to see if AdvancedChat is loaded.

**Comment by UnlikePaladin** [comment]
We're not supporting a mod that outright replaces the chat screen for the foreseeable future
